# Setup
title:        Mechatronics Intelligence Lab
tagline:      메카트로닉스 시스템의 지능형 상태관리 
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Hong Youngsun
  url:        https://mechatronics-intelligence-lab.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
