
# Setup
title: Mechatronics Intelligence Lab
description: 전기차, 배터리 및 파워트레인을 포함하는 메카트로닉스 시스템에 대해 연구합니다.
show_downloads: true

baseurl: ""
url: "https://mechatronics-intelligence-lab.github.io" 

google_analytics:

date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['research', 'people', 'publication', 'contact']
