
- date: 2020-03-01
  title: "전기차 통합유지보수 실증기반 구축"
  author: "한국생산기술연구원, 한국자동차연구원, 부품디비, 제주대학교"
  state: "산업부"

- date: 2022-04-01
  title: "차량 전력이용 효율 제고를 위한 디지털 트윈 활용 전원체계 최적화 기술개발"
  author: "한국자동차연구원, 한국생산기술연구원, 만도"
  state: "산업부"

- date: 2023-09-01
  title: "전기차 배터리 퇴화고장진단 및 관련시험 분석기술개발"
  author: "한국생산기술연구원"
  state: "LG에너지솔루션"

- date: 2023-10-01
  title: "타이어 마모 진단 기술개발을 위한 전기택시 주행신호 취득 및 타이어 마모실측"
  author: "한국생산기술연구원"
  state: "현대자동차"

- date: 2024-04-01
  title: "고부하 소모전장품을 위한 요소부품 기술개발"
  author: "한국생산기술연구원, 만도, 한국자동차연구원"
  state: "산업부"

- date: 2025-10-01
  title: "생성형 인공지능 기술을 이용한 사용후 배터리 모듈 진단 시스템 개발"
  author: "모나주식회사, 전북대학교, 한국과학기술원"
  state: "전북테크노파크"
